package com.haylion.entity;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.id
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.modulename
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    private String modulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.parentid
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.parentname
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    private String parentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.langid
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    private Integer langid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.id
     *
     * @return the value of t_type.id
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.id
     *
     * @param id the value for t_type.id
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.modulename
     *
     * @return the value of t_type.modulename
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.modulename
     *
     * @param modulename the value for t_type.modulename
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.parentid
     *
     * @return the value of t_type.parentid
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.parentid
     *
     * @param parentid the value for t_type.parentid
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.parentname
     *
     * @return the value of t_type.parentname
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public String getParentname() {
        return parentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.parentname
     *
     * @param parentname the value for t_type.parentname
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public void setParentname(String parentname) {
        this.parentname = parentname == null ? null : parentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.langid
     *
     * @return the value of t_type.langid
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public Integer getLangid() {
        return langid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.langid
     *
     * @param langid the value for t_type.langid
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    public void setLangid(Integer langid) {
        this.langid = langid;
    }
}