package com.haylion.entity;

import java.util.Date;

public class VisitorCounter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visitorcounter.id
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visitorcounter.vdate
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    private String vdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visitorcounter.vnum
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    private Integer vnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visitorcounter.id
     *
     * @return the value of t_visitorcounter.id
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visitorcounter.id
     *
     * @param id the value for t_visitorcounter.id
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visitorcounter.vdate
     *
     * @return the value of t_visitorcounter.vdate
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    public String getVdate() {
        return vdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visitorcounter.vdate
     *
     * @param vdate the value for t_visitorcounter.vdate
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    public void setVdate(String vdate) {
        this.vdate = vdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visitorcounter.vnum
     *
     * @return the value of t_visitorcounter.vnum
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    public Integer getVnum() {
        return vnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visitorcounter.vnum
     *
     * @param vnum the value for t_visitorcounter.vnum
     *
     * @mbggenerated Thu Mar 29 15:01:52 CST 2018
     */
    public void setVnum(Integer vnum) {
        this.vnum = vnum;
    }
}