package com.haylion.dao;

import java.util.List;
import java.util.Map;

import com.haylion.entity.Module;

public interface ModuleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated Sat Mar 24 10:25:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated Sat Mar 24 10:25:35 CST 2018
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated Sat Mar 24 10:25:35 CST 2018
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated Sat Mar 24 10:25:35 CST 2018
     */
    List<Module> selectByPrimaryKey(Module module);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated Sat Mar 24 10:25:35 CST 2018
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated Sat Mar 24 10:25:35 CST 2018
     */
    int updateByPrimaryKey(Module record);
    
    List<Module> selectType(Module record);

	List<Module> list(Map<String, Object> map);
}