package com.haylion.dao;

import java.util.List;

import com.haylion.entity.Type;

public interface TypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    List<Type> selectByPrimaryKey(Type type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Wed May 09 15:26:37 CST 2018
     */
    int updateByPrimaryKey(Type record);
}